export default {
  user: null,
  onlinelist: [],
  selected_login_db: null,
  account_menu: null,
  server_menu: null,
  rank_gender: null,
  rank_province: null,
  staff_rank: null,
  user_rank: null,
  staff_list: null,
  user_list: null,
  admin_card: false,
  group_games_list: null,
  path_to_server: 'http://localhost:7798/',
  ip: '51.83.179.240',
  hidden_siedbar: false,
  user_list_to_search: null,
  hiden_content_siedbar: true
}
